default_platform(:android)

platform :android do



desc "Increment version code"
 lane :increment_vc do
 increment_version_code(
       gradle_file_path: "./app/build.gradle",
 )
end
desc "Build"
lane :build do
  gradle(
     task: "assemble",
     build_type: "Debug"
   )
end


  desc "Lane for distributing app using Firebase App Distributions"
  lane :distribute do
    firebase_app_distribution(
      app: ENV["APP_ID"],
      android_artifact_type: "APK",
      apk_path: "../android/app/build/outputs/apk/debug/app-debug.apk",
      debug: true,
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end
