default_platform(:android)

platform :android do

desc "Increment version code"
 lane :increment_vc do
 increment_version_code(
       gradle_file_path: "./app/build.gradle",
 )
end
desc "Custom increment version code"
lane :custom_increment_vc do
  gradle_file = "app/build.gradle"
  version_code = `grep versionCode #{gradle_file} | awk '{print $2}'`.to_i
  new_version_code = github.run_number
  sh "sed -i 's/versionCode #{version_code}/versionCode #{new_version_code}/' #{gradle_file}"
  puts "Updated version code to #{new_version_code}"
end
desc "Build"
lane :build do
  custom_increment_vc
  gradle(
     task: "assemble",
     build_type: "debug"
   )
end

  desc "Lane for distributing app using Firebase App Distributions"
  lane :distribute do
    firebase_app_distribution(
      app: ENV["APP_ID"],
      android_artifact_type: "APK",
      apk_path: "../android/app/build/outputs/apk/debug/app-debug.apk",
      debug: true,
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end
