name: "Build Android app"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' 
          bundler-cache: true
      - name: Install Bundler
        run: gem install bundler     
      
      - name: Install gems
        run: bundle install
      
      - name: Set up Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash  
      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Yarn Install
        run: |
             npm i -g corepack
             yarn install             
      # - name: Build application
      #   run: |
      #        cd ./android
      #        ./gradlew assembleDebug             

          
      - name: Run Fastlane apk
        working-directory: ./android
        run: |
          chmod 777 -R /var/lib/gems/
          bundle exec fastlane add_plugin get_version_name
          bundle exec fastlane add_plugin increment_version_name
          bundle exec fastlane add_plugin increment_version_code
          bundle exec fastlane android build --verbose
          bundle exec fastlane android distribute --verbose 
        env:
          APP_ID: ${{ secrets.APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}

      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3          
