name: "Build Android app"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FASTLANE_DISABLE_COLORS: "1"
      FASTLANE_SKIP_UPDATE_CHECK: "1"
      FASTLANE_NO_EXECUTE: "0"    
    steps:
      - name: keytool command
        run: keytool -genkey -v -keystore releasekey.jks -keyalg RSA -keysize 2048 -validity 10000 -alias releaseley
      - name: Openssl command
        run: openssl base64 < releasesigningkey.jks | tr -d '\n' | tee releasesigningkey.jks.base64.txt    
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' 
          bundler-cache: true         
      - name: Install Bundler
        run: gem install bundler     
      
      - name: Install gems
        run: bundle install
      
      - name: Set up Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash  
      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Yarn Install
        run: |
             npm i -g corepack
             yarn install             
                     
      - name: Run Fastlane apk
        working-directory: ./android
        run: |

          bundle exec fastlane android increment_vc --verbose 
          bundle exec fastlane android build --verbose
          bundle exec fastlane android distribute --verbose 
        env:
          APP_ID: ${{ secrets.APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION
          
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        with:
          releaseDirectory: ./android/app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}      
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}  

      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3          
